# Directory to store data used by qotd.
# data_dir = "/var/lib/qotd"

# Set `enable_vendors` to enable only the specified vendors.
# If not set, all configured vendors are enabled by default.
# enable_vendors = [ "theysaidso", "zenquotes" ]

[vendors.theysaidso]
name = "They Said So"
homepage = "https://theysaidso.com"
endpoint = "https://quotes.rest/qod"

# GJSON Paths to query quote information in the API response.
# GJSON Path syntax: https://github.com/tidwall/gjson/blob/master/SYNTAX.md
[vendors.theysaidso.queries]
quote = "contents.quotes.0.quote"
author = "contents.quotes.0.author"
url = "contents.quotes.0.permalink"

[vendors.zenquotes]
name = "ZenQuotes.io"
homepage = "https://zenquotes.io"
endpoint = "https://zenquotes.io/api/random"

[vendors.zenquotes.queries]
quote = "0.q"
author = "0.a"
